kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4
mirror:
  platform:
    architectures:
    - "amd64"
    channels:
    - name: stable-4.16
      minVersion: 4.16.15
      maxVersion: 4.16.15
      type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    full: false
    packages:
    - name: 'advanced-cluster-management'
      minVersion: 'v2.12.0'
      maxVersion: 'v2.12.0'
      channels:
      - name: 'release-2.12'
    - name: 'multicluster-engine'
      minVersion: 'v2.7.1'
      maxVersion: 'v2.7.1'
      channels:
      - name: 'stable-2.7'
    - name: 'topology-aware-lifecycle-manager'
      minVersion: 'v4.16.2'
      maxVersion: 'v4.16.2'
      channels:
      - name: 'stable'
    - name: 'openshift-gitops-operator'
      minVersion: 'v1.14.2'
      maxVersion: 'v1.14.2'
      channels:
      - name: 'latest'
    - name: 'odf-operator'
      minVersion: 'v4.16.3-rhodf'
      maxVersion: 'v4.16.3-rhodf'
      channels:
      - name: 'stable-4.16'
    - name: 'ocs-operator'
      minVersion: 'v4.16.3-rhodf'
      maxVersion: 'v4.16.3-rhodf'
      channels:
      - name: 'stable-4.16'
    - name: 'odf-csi-addons-operator'
      minVersion: 'v4.16.3-rhodf'
      maxVersion: 'v4.16.3-rhodf'
      channels:
      - name: 'stable-4.16'
    - name: 'local-storage-operator'
      minVersion: 'v4.16.0-202411190033'
      maxVersion: 'v4.16.0-202411190033'
      channels:
      - name: 'stable'
    - name: 'mcg-operator'
      minVersion: 'v4.16.3-rhodf'
      maxVersion: 'v4.16.3-rhodf'
      channels:
      - name: 'stable-4.16'
    - name: 'cluster-logging'
      minVersion: 'v6.1.0'
      maxVersion: 'v6.1.0'
      channels:
      - name: 'stable-6.0'
    - name: 'odf-prometheus-operator'
      minVersion: 'v4.16.3-rhodf'
      maxVersion: 'v4.16.3-rhodf'
      channels:
      - name: 'stable-4.16'
    - name: 'recipe'
      minVersion: 'v4.16.3-rhodf'
      maxVersion: 'v4.16.3-rhodf'
      channels:
      - name: 'stable-4.16'
    - name: 'rook-ceph-operator'
      minVersion: 'v4.16.3-rhodf'
      maxVersion: 'v4.16.3-rhodf'
      channels:
      - name: 'stable-4.16'
  additionalImages:
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.16.0
  - name: registry.redhat.io/multicluster-engine/must-gather-rhel9:v2.6
  - name: registry.redhat.io/rhacm2/acm-must-gather-rhel9:v2.11
  - name: registry.redhat.io/openshift-gitops-1/must-gather-rhel8:v1.12.0
  - name: registry.redhat.io/openshift-logging/cluster-logging-rhel9-operator:v5.8.5
  helm: {}
