apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00_rhacm_deployment.yaml
  - 01_talm_deployment.yaml
  - 02_mce_deployment.yaml
#  - 03_observability_deployment.yaml
  - 99_00_lso_deployment.yaml
  - 99_01_odf_deployment.yaml
